return {
  "mg979/vim-visual-multi",
  cmd = {
    "VMap",
    "VNew",
    "VNewShell",
    "VS",
    "VSCode",
    "VSDebug",
    "VSDebugger",
    "VSTerminal",
    "VSTerminalOpen",
    "VSTerminalSend",
    "VSTerminalSendRaw",
    "VSTerminalToggle",
    "VSTerminalToggleSplit",
    "VSTerminalVSCode",
    "VSTerminalWindows",
    "VToggle",
    "VToggleLine",
    "VToggleRange",
    "VW",
    "VWSplit",
  },
  -- event = "BufRead",
  -- config = function()
  --   vim.g.VM_maps = {
  --     ["Find Under"] = "<C-m>",
  --     ["Find Subword Under"] = "<C-m>",
  --     ["Select All"] = "<C-d>",
  --     ["Skip Region"] = "<C-x>",
  --     ["Remove Region"] = "<C-q>",
  --     ["Undo"] = "u",
  --     ["Redo"] = "<C-r>",
  --   }
  -- end,
}
