return {
  { import = "plugins.local.binary-peek" },
  { import = "plugins.local.js-playground" },
  { import = "plugins.local.popurri" },
  { import = "plugins.local.yerbreak" },
  { import = "plugins.spec.coc" },
  { import = "plugins.spec.autopairs" },
  { import = "plugins.spec.better-escape" },
  { import = "plugins.spec.ccc" },
  { import = "plugins.spec.cd-project" },
  { import = "plugins.spec.cloak" },
  { import = "plugins.spec.codesnap" },
  { import = "plugins.spec.comment" },
  { import = "plugins.spec.crates" },
  { import = "plugins.spec.dap-python" },
  { import = "plugins.spec.dap-ui" },
  { import = "plugins.spec.dap-virtual-text" },
  { import = "plugins.spec.diffview" },
  { import = "plugins.spec.dressing" },
  { import = "plugins.spec.dropbar" },
  { import = "plugins.spec.edgy" },
  { import = "plugins.spec.fugitive" },
  { import = "plugins.spec.gitsigns" },
  { import = "plugins.spec.gleam" },
  { import = "plugins.spec.goto-preview" },
  { import = "plugins.spec.grug-far" },
  { import = "plugins.spec.harpoon" },
  { import = "plugins.spec.helpview" },
  { import = "plugins.spec.hop" },
  { import = "plugins.spec.lsp-signature" },
  { import = "plugins.spec.markview" },
  { import = "plugins.spec.matchup" },
  { import = "plugins.spec.md-preview" },
  { import = "plugins.spec.multicursor" },
  { import = "plugins.spec.neogit" },
  { import = "plugins.spec.notify" },
  { import = "plugins.spec.obsidian" },
  { import = "plugins.spec.oil-vcs-status" },
  { import = "plugins.spec.oil" },
  { import = "plugins.spec.outline" },
  { import = "plugins.spec.precognition" },
  { import = "plugins.spec.rainbow-delimiters" },
  { import = "plugins.spec.regexplainer" },
  { import = "plugins.spec.rustaceanvim" },
  { import = "plugins.spec.screenkey" },
  { import = "plugins.spec.scrolleof" },
  { import = "plugins.spec.supermaven" },
  { import = "plugins.spec.tiny-code-action" },
  { import = "plugins.spec.tiny-inline-diagnostic" },
  { import = "plugins.spec.todo-comments" },
  { import = "plugins.spec.treesitter-textobjects" },
  { import = "plugins.spec.trouble" },
  { import = "plugins.spec.ts-autotag" },
  { import = "plugins.spec.ts-context-commentstring" },
  { import = "plugins.spec.undo-tree" },
  { import = "plugins.spec.vim-astro" },
  { import = "plugins.spec.vim-illuminate" },
  { import = "plugins.spec.vim-visual-multi" },
  { import = "plugins.spec.zen-mode" },
  { import = "plugins.spec.lazygit" },
  { import = "plugins.spec.markdown" },
  { import = "plugins.spec.flutter" },
  { import = "plugins.spec.rust" },
  { import = "plugins.spec.go" },
  { import = "plugins.spec.leap" },
  { import = "plugins.spec.conda" },
  { import = "plugins.spec.iron" },
  { import = "plugins.spec.jupyter" },
  { import = "plugins.spec.neoterm" },
  { import = "plugins.spec.pug" },
  { import = "plugins.override.base46" },
  { import = "plugins.override.blankline" },
  { import = "plugins.override.cmp" },
  { import = "plugins.override.conform" },
  { import = "plugins.override.lspconfig" },
  { import = "plugins.override.luasnip" },
  { import = "plugins.override.mason" },
  { import = "plugins.override.nvim-colorizer" },
  { import = "plugins.override.nvim-tree" },
  { import = "plugins.override.nvim-treesitter" },
  { import = "plugins.override.nvim-web-devicons" },
  { import = "plugins.override.telescope" },
  { import = "plugins.override.ui" },
  { import = "plugins.override.whichkey" },
  { import = "plugins.override.leetcode" },
  { import = "plugins.override.notebookNavigator" },
  { import = "plugins.override.workspace" },
  { import = "plugins.override.quarto" },
  -- { import = "plugins.override.vim-slime" },

  -- plugins (local)
  -- plugins
  {
    "neoclide/coc.nvim",
    branch = "release",
    build = "yarn install --frozen-lockfile",
    config = function()
      require "plugins.local.coc"
    end,
    dependencies = {
      "neovim/nvim-lspconfig",
      "nvim-lua/plenary.nvim",
      "hrsh7th/cmp-nvim-lsp",
      "hrsh7th/cmp-buffer",
      "hrsh7th/cmp-path",
      "hrsh7th/cmp-cmdline",
      "hrsh7th/cmp-nvim-lsp-signature-help",
      "saadparwaiz1/cmp_luasnip",
      "L3MON4D3/LuaSnip", -- For snippets
      "rafamadriz/friendly-snippets", -- For snippets
    },
  },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  {
    "nvim-treesitter/playground",
    dependencies = { "nvim-treesitter/nvim-treesitter" },
  },
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
    dependencies = { "nvim-treesitter/nvim-treesitter" },
  },
  { "nvim-treesitter/nvim-treesitter-refactor" }, -- refactoring
  { "vim-ruby/vim-ruby" }, -- Syntax highlighting
  { "tpope/vim-rails" }, -- rails
  { "tpope/vim-bundler" },
  { "tpope/vim-unimpaired" },
  { "plasticboy/vim-markdown" },
  { "jpalardy/vim-slime", lazy = false },
}
